### PR TITLE
filter string and updated tests

### PR DESCRIPTION
**Pull request by vietnguyengit**

### CODE REVIEW

**Review by utas-raymondng — CHANGES_REQUESTED** [review]
Instead of change in code, is it easier to do it in elastic ?
``
"index": {
    "analysis": {
      "filter": {
        "remove_uuids": {
          "type": "pattern_replace",
          "pattern": "[a-fA-F0-9]{32}",  // Regular expression to match UUIDs
          "replacement": ""
        },
        "my_shingle_filter": {
          "type": "shingle",
          "min_shingle_size": 2,
          "max_shingle_size": 3,
          "output_unigrams": true
        }
      },
      "analyzer": {
        "my_analyzer": {
          "type": "custom",
          "tokenizer": "standard",
          "filter": ["lowercase", "remove_uuids", "my_shingle_filter"]
        }
      }
    }
```

**Comment by utas-raymondng** [comment]
Also pure number can be remove ?

**Comment by utas-raymondng** [comment]
And single char like "m"

**Comment by vietnguyengit** [comment]
> Instead of change in code, is it easier to do it in elastic ? `` "index": { "analysis": { "filter": { "remove_uuids": { "type": "pattern_replace", "pattern": "[a-fA-F0-9]{32}", // Regular expression to match UUIDs "replacement": "" }, "my_shingle_filter": { "type": "shingle", "min_shingle_size": 2, "max_shingle_size": 3, "output_unigrams": true } }, "analyzer": { "my_analyzer": { "type": "custom", "tokenizer": "standard", "filter": ["lowercase", "remove_uuids", "my_shingle_filter"] } } }

didn't think about that path, I'll try

**Review by utas-raymondng — APPROVED** [review]
LGTM, please reload after deployed to edge thanks

**Pull request merged**
